### PR TITLE
fedc: switch to anitya and fix url templates

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by jakobjakobson13** [comment]
LGTM, but one short question and one comment before I merge it.
The question: What are the advantages of your version checker compared to the regex version?
~~The comment: As far as I [heard](https://github.com/flathub/flathub/issues/1820#issuecomment-691284774) only the default branch gets checked for new versions. So your pull request won't have any effect on this branch unless it becomes the default branch. Are you aware of that or is my link outdated?~~ Sorry, I did not see that the default branch changed to 20.08.

**Comment by Lctrs** [comment]
> The question: What are the advantages of your version checker compared to the regex version?

It makes the version update check more bulletproof to changes to the design of https://golang.org/dl/ by relying on https://release-monitoring.org/.

**Comment by jakobjakobson13** [comment]
Okay, let's change the checker then.
Should we delete the `armv6l` section while we are at it? The flathub bots don't seem to build it anyway.

**Comment by jakobjakobson13** [comment]
> Should we delete the `armv6l` section while we are at it? The flathub bots don't seem to build it anyway.

@Lctrs Do you want to do this in your pull request? Otherwise I would do it after the merge.

**Comment by Lctrs** [comment]
@jakobjakobson13 Done.

**Comment by gasinvein** [comment]
You should also change versions in appdata, then. Anitya returns versions without `go` prefix, so current ones would become inconsistent, you'll need to remove `go` prefix from existing `<release>` entries.

**Comment by Lctrs** [comment]
@gasinvein there are none in the `20.08` branch.

**Comment by jakobjakobson13** [comment]
> @gasinvein there are none in the `20.08` branch.

But there should be some, shouldn't they? The `x-checker-data` were identical in the 19.08 and the 20.08 branch and only the `flathub.json` file differed in the line `"automerge-flathubbot-prs": true`. So, do we need to put this as well in the `flathub.json` file?

**Comment by gasinvein** [comment]
I think the external data checker will add releases for you on next update.

**Comment by jakobjakobson13** [comment]
> I think the external data checker will add releases for you on next update.

Yes, well, my checker syntax was constructed too simple and thought the 1.16 beta version was the current stable version. But I hope this should be solved now.

**Comment by gasinvein** [comment]
BTW [flatpak-external-data-checker](https://github.com/orgs/flathub/packages/container/package/flatpak-external-data-checker) is now available as a docker image on ghcr.io, so you can use/test it locally.

**Pull request merged**
