### PR TITLE
Update to go 1.11

### PR DESCRIPTION
**Pull request by csoriano1618**
Necessary for mod support

### CODE REVIEW

**Comment by csoriano1618** [comment]
No idea why this fails CI, it builds locally and looking at the code is clear the replaced strings are just that...

**Comment by barthalion** [comment]
bot, build

**Comment by csoriano1618** [comment]
bot, build

**Comment by barthalion** [comment]
Thanks!

**Comment by csoriano1618** [comment]
np! Do you know if this inmediatily available? Or is there some significant delay (a day or so)?

**Comment by barthalion** [comment]
I just clicked "publish" button for 1.6. Looks like official build for 18.08 got lost between buildbot restarts so I retriggered it and I'll publish it when it builds.

**Comment by csoriano1618** [comment]
ah thanks, excellent! 1.6 it's what I need, since it's what vscode uses. I will wait for that then before starting today's code work shift :-)

**Pull request merged**
